


flops_util2 = dict()

flops_util2['eth'] = dict()
flops_util2['eth']['Downscale'] = dict()
flops_util2['eth']['Convolution'] = dict()
flops_util2['eth']['Octaves'] = dict()
flops_util2['eth']['GaussianKernelGeneration'] = dict()
flops_util2['eth']['GaussianPyramid'] = dict()
flops_util2['eth']['DOGPyramid'] = dict()
flops_util2['eth']['GradientAndRotationPyramids'] =dict()
flops_util2['eth']['Histogram'] = dict()
flops_util2['eth']['ExtremaRefinement'] = dict()
flops_util2['eth']['KeypointDetection'] = dict()
flops_util2['eth']['ExtractDescriptor'] = dict()

flops_util2['ez'] = dict()
flops_util2['ez']['Downscale'] = dict()
flops_util2['ez']['Convolution'] =dict()
flops_util2['ez']['Octaves'] = dict()
flops_util2['ez']['GaussianKernelGeneration'] = dict()
flops_util2['ez']['GaussianPyramid'] = dict()
flops_util2['ez']['DOGPyramid'] =dict()
flops_util2['ez']['GradientAndRotationPyramids'] = dict()
flops_util2['ez']['Histogram'] = dict()
flops_util2['ez']['ExtremaRefinement'] = dict()
flops_util2['ez']['KeypointDetection'] =dict()
flops_util2['ez']['ExtractDescriptor'] =dict()

rw_util = dict()

rw_util['eth'] = dict()
rw_util['eth']['Downscale'] = dict()
rw_util['eth']['Convolution'] = dict()
rw_util['eth']['Octaves'] = dict()
rw_util['eth']['GaussianKernelGeneration'] = dict()
rw_util['eth']['GaussianPyramid'] = dict()
rw_util['eth']['DOGPyramid'] = dict()
rw_util['eth']['GradientAndRotationPyramids'] =dict()
rw_util['eth']['Histogram'] = dict()
rw_util['eth']['ExtremaRefinement'] = dict()
rw_util['eth']['KeypointDetection'] = dict()
rw_util['eth']['ExtractDescriptor'] = dict()

rw_util['ez'] = dict()
rw_util['ez']['Downscale'] = dict()
rw_util['ez']['Convolution'] =dict()
rw_util['ez']['Octaves'] = dict()
rw_util['ez']['GaussianKernelGeneration'] = dict()
rw_util['ez']['GaussianPyramid'] = dict()
rw_util['ez']['DOGPyramid'] =dict()
rw_util['ez']['GradientAndRotationPyramids'] = dict()
rw_util['ez']['Histogram'] = dict()
rw_util['ez']['ExtremaRefinement'] = dict()
rw_util['ez']['KeypointDetection'] =dict()
rw_util['ez']['ExtractDescriptor'] =dict()