name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure project
      run: |
        mkdir build
        cd build && cmake .. -DCMAKE_BUILD_TYPE=Release
    - name: Build project
      run: |
        cd build && make VERBOSE=1
    - name: Run tests
      run: |
        cd build && ./tester
    - name: Create build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/
  profile:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install prerequisites
      run: |
        sudo apt-get -qq install rename
    - uses: actions/download-artifact@v2
      with:
        name: build
        path: build/
    - name: Run tests
      run: |
        chmod +x build/tester
        for file in data/*.pgm; do IMAGE=$file ./build/tester; done
    - name: Build flamegraph
      run: |
        sudo sh -c 'echo 0 > /proc/sys/kernel/perf_event_paranoid'
        cd build && make flamegraph
    - name: Build artifact
      run: |
        cp build/flamegraph.svg logs
        cd logs && rename 's|:|-|g' *
    - name: Create logs artifact
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/
    - name: Post to discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: "Build for ${{ github.sha }} on ${{ github.ref }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        file: "./rel/flamegraph.svg"
