name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure project
      run: |
        mkdir build
        cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DMEASUREMENT_MODE=chrono
    - name: Build project
      run: |
        cd build && make VERBOSE=1
    - name: Run tests
      run: |
        cd build && ./tester
    - name: Create build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build/
  profile:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        name: build
        path: build/
    - name: Build flamegraph
      continue-on-error: true
      env:
        IMAGE: auto-1080p.pgm
        RUNS: 1000
      run: |
        chmod +x build/tester
        sudo sh -c 'echo 0 > /proc/sys/kernel/perf_event_paranoid'
        cd build && make flamegraph &> output.log
    - name: Build artifact
      continue-on-error: true
      run: |
        cp build/flamegraph.svg build/output.log logs
    - name: Create logs artifact
      continue-on-error: true
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/
    - name: Post to discord
      continue-on-error: true
      run: echo "::set-env name=OUTPUT::$(cat build/output.log)"
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        message: "Build for ${{ github.sha }} on ${{ github.ref }}: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
```
${{ env.OUTPUT }}
```"
